In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

In [2]:
import numpy as np

In [3]:
A = np.arange(6).reshape(2,3)
B = np.arange(1,7).reshape(2,3)
a = np.arange(2)
b = np.arange(3)
c = np.arange(3)
A.shape, B.shape, a.shape, b.shape,c.shape

((2, 3), (2, 3), (2,), (3,), (3,))

In [4]:
print(">>> A")
A
print(">>> B")
B
print(">>> a")
a
print(">>> b")
b
print(">>> c")

>>> A


array([[0, 1, 2],
       [3, 4, 5]])

>>> B


array([[1, 2, 3],
       [4, 5, 6]])

>>> a


array([0, 1])

>>> b


array([0, 1, 2])

>>> c


In [5]:
# 矩阵 - 矩阵
np.multiply(A, B)
A*B
np.dot(A,B.T)
np.matmul(A,B.T)

array([[ 0,  2,  6],
       [12, 20, 30]])

array([[ 0,  2,  6],
       [12, 20, 30]])

array([[ 8, 17],
       [26, 62]])

array([[ 8, 17],
       [26, 62]])

In [6]:
# 矩阵 - 数组
np.multiply(A, b)
A*b
np.dot(A,b)
np.matmul(A,b)

array([[ 0,  1,  4],
       [ 0,  4, 10]])

array([[ 0,  1,  4],
       [ 0,  4, 10]])

array([ 5, 14])

array([ 5, 14])

In [7]:
# 数组 - 矩阵
np.multiply(b,A)
b*A
np.dot(a,A)
np.matmul(a,A)

array([[ 0,  1,  4],
       [ 0,  4, 10]])

array([[ 0,  1,  4],
       [ 0,  4, 10]])

array([3, 4, 5])

array([3, 4, 5])

In [8]:
# 数组 - 数组
np.multiply(b,c)
b*c
np.dot(b,c)
np.matmul(b,c)

array([0, 1, 4])

array([0, 1, 4])

5

5

In [13]:
# 标量 - 矩阵
np.multiply(2,A)
2*A
np.dot(2,A)
np.matmul(2,A)  # 不能与标量相乘

array([[ 0,  2,  4],
       [ 6,  8, 10]])

array([[ 0,  2,  4],
       [ 6,  8, 10]])

array([[ 0,  2,  4],
       [ 6,  8, 10]])

ValueError: Scalar operands are not allowed, use '*' instead

In [10]:
2 *A

array([[ 0,  2,  4],
       [ 6,  8, 10]])